[package]
name = "chemgrouper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inquire = "0.7.5"
petgraph = "0.6.5"
tinyjson = "2.5.1"
